USE [ShareIdea]
GO

/****** Object:  Table [dbo].[Voices]    Script Date: 6.17.2016 6:42:06 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Voices](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[idChoice] [int] NULL,
	[Value] [int] NULL,
 CONSTRAINT [PK_Voices] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


